[package]
name = "renderer"
version = "0.1.0"
authors = ["Educorreia932 <skelozard1@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23.12"
nalgebra = "0.20"   
rand = "0.8.2"

[build]
rustc-flags = "-A dead_code"